# Generated by Django 3.1.3 on 2020-11-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='type',
            field=models.CharField(default='peer', max_length=128),
            preserve_default=False,
        ),
    ]
